config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: ''
  root 'video_share#index'

  resources :user, only: [:new, :create]
  resources :session
  get '/signup', to: 'user#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  post '/share', to: 'video_share#create'
  get '/share', to: 'video_share#new'
  get '/videos', to: 'video_share#index'
  get '/my_videos', to: 'video_share#my_videos', as: 'my_videos'
  delete '/my_videos/:id', to: 'video_share#destroy', as: 'delete_video'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :video_shares
  validates :username, presence: true, uniqueness: true
end

app/models/video_share.rb
class VideoShare < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  # configuration for Yt gem
  Yt.configure do |config|
    config.api_key = ENV['YOUTUBE_API_KEY']
    config.log_level = :debug
  end

  private
  def authenticate_user!
    unless current_user
      redirect_to new_user_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    flash[:alert] = nil
    flash[:notice] = nil
  end

  def create
    user = User.find_by(username: params[:username])
    if (user && user.authenticate(params[:password]))
      session[:current_user_id] = user.id
      flash[:notice] = "Logged in"
      redirect_to root_path
    else
      flash[:alert] = 'Invalid username or password'
      render :new
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    flash[:alert] = nil
    flash[:notice] = nil
  end

  def index
  end

  def create
    check_existed_user = User.find_by(username: params[:username])
    if (check_existed_user)
      flash[:alert] = "Username already created"
      @user = User.new(username: user_params[:username])
      return render :new
    end

    if (user_params[:password] != user_params[:password_confirmation])
      flash[:alert] = "Wrong confirmation password"
      @user = User.new(username: user_params[:username])
      return render :new
    end

    @user = User.new(user_params)
    if (@user.save)
      session[:current_user_id] = @user.id
      flash[:notice] = "User created."
      redirect_to root_path
    end
  end

  private
  def user_params
    params.permit(:username, :password, :password_confirmation)
  end
end

app/controllers/video_share_controller.rb
class VideoShareController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :my_videos, :destroy]

  def index
    @videos = VideoShare.all.order(created_at: :desc)
  end

  def new
    if current_user.nil?
      redirect_to root_path
    end
    flash[:alert] = nil
    flash[:notice] = nil
  end

  def create
    if current_user.nil?
      flash[:alert] = "You need to sign in or sign up before continuing."
      return
    end
    is_video_existed = VideoShare.find_by(url: params[:url], user_id: current_user.id)
    if is_video_existed
      flash[:alert] = "You have already shared this video"
      return render :new
    end
    unless valid_youtube_url?(params[:url])
      flash[:alert] = "Invalid URL"
      return render :new
    end
    video_info = Yt::Video.new url: params[:url]
    title = video_info.title
    description = video_info.description
    thumbnail_url = video_info.thumbnail_url
    video = current_user.video_shares.new(url: params[:url], title: title, description: description, thumbnail_url: thumbnail_url)
    if video.save
      redirect_to root_path
    else
      flash[:alert] = "Fail to share video"
      render :new
    end
  end

  def my_videos
    @my_videos = current_user.video_shares.all.order(created_at: :desc)
  end

  def destroy
    @share = current_user.video_shares.find(params[:id])
    @share.destroy
    redirect_to root_path
  end

  private
  def valid_youtube_url?(url)
    url =~ %r{\A(https?://)?(www\.)?(youtube\.com/watch\?v=|youtu\.be/)[a-zA-Z0-9_-]{11}}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/video_share_helper.rb
module VideoShareHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Remitano Share Youtube Videos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <h2><%= link_to 'Funny Movies', root_path %></h2>
      <div class="right-header">
        <% if current_user %>
          <button class="btn btn-share-video"><%= button_to 'My shared video', my_videos_path, method: :get %></button>
          <button class="btn btn-share-video"><%= button_to 'Share video', share_path, method: :get %></button>
          <p>Welcome <%= current_user.username %>!</p>
          <button class="btn btn-logout"><%= button_to 'Logout', logout_path, method: :delete %></button>
        <% else %>
          <button class="btn btn-login"><%= button_to 'Login', login_path, method: :get %></button>
          <button class="btn btn-signup"><%= button_to 'Signup', signup_path, method: :get %></button>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

<style>

</style>

app/views/session/new.html.erb
<h1>Log in</h1>

<% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<%= form_tag login_path do %>
  <div class="form-group">
    <%= label_tag :username %>
    <%= text_field_tag :username, nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, class: 'form-control' %>
  </div>

  <%= submit_tag "Log in", class: 'btn btn-primary' %>

  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <span><%= flash[:alert] %></span>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <span><%= flash[:notice] %></span>
    </div>
  <% end %>

  <p>If you don't have an account? <%= link_to "Sign Up", signup_path %></p>
<% end %>

app/views/user/new.html.erb
<h1>Sign up</h1>

<div class="container">
  <h1>Create an Account</h1>
  <%= form_with model: @user, url: user_index_path, local: true do |form| %>
    <div class="form-group">
      <%= form.label :username %>
      <%= form.text_field :username, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
    <%= form.submit "Create Account", class: "btn btn-primary" %>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <span><%= flash[:alert] %></span>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <span><%= flash[:notice] %></span>
    </div>
  <% end %>
  <p>Already have an account? <%= link_to "Sign In", login_path %></p>
</div>

app/views/video_share/index.html.erb
<div class="video-row">
  <% @videos.each do |video| %>
    <div class="col-md-4">
      <div class="card mb-4 box-shadow">
        <img class="card-img" src="<%= video.thumbnail_url %>" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= link_to video.title, video.url, target: "_blank" %></h5>
          <p class="card-text"><%= video.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/video_share/my_videos.html.erb
<h1>My Shared Videos</h1>
<p>You shared <%= @my_videos.count %> videos</p>
<div class="video-row">
  <% @my_videos.each do |video| %>
    <div class="col-md-4">
      <div class="card mb-4 box-shadow">
        <img class="card-img" src="<%= video.thumbnail_url %>" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= link_to video.title, video.url, target: '_blank' %></h5>
          <p class="card-text"><%= video.description %></p>
          <button class="btn-delete-video">
            <%= button_to "Delete", delete_video_path(video.id), method: :delete, data: { confirm: "Are you sure you want to delete this video?" }, class: "btn btn-sm btn-danger" %>
          </button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/video_share/new.html.erb
<h1>Share a video</h1>

<div class="share-video">
  <%= form_tag share_path, method: :post do %>
    <div>
      <%= label_tag :url, "YouTube URL" %>
      <%= text_field_tag :url %>
    </div>
    <%= submit_tag "Submit" %>
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <span><%= flash[:alert] %></span>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <span><%= flash[:notice] %></span>
      </div>
    <% end %>
  <% end %>
</div>